name: Continuous Integration
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.5

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y check nasm

      - name: Build the tests
        run: |
          cd tests
          make

      - name: Run the tests
        run: |
          cd tests
          ./test
